sudo apt install kali-tools-802-11
sudo apt install kali-tools-bluetooth
sudo apt install kali-tools-crypto-stego
sudo apt install kali-tools-database
sudo apt install kali-tools-detect
sudo apt install kali-tools-exploitation
sudo apt install kali-tools-forensics
sudo apt install kali-tools-fuzzing
sudo apt install kali-tools-gpu
sudo apt install kali-tools-hardware
sudo apt install kali-tools-identify
sudo apt install kali-tools-information-gathering
sudo apt install kali-tools-passwords
sudo apt install kali-tools-post-exploitation
sudo apt install kali-tools-protect
sudo apt install kali-tools-recover
sudo apt install kali-tools-reporting
sudo apt install kali-tools-respond
sudo apt install kali-tools-reverse-engineering
sudo apt install kali-tools-rfid
sudo apt install kali-tools-sdr
sudo apt install kali-tools-sniffing-spoofing
sudo apt install kali-tools-social-engineering
sudo apt install kali-tools-top10
sudo apt install kali-tools-voip
sudo apt install kali-tools-vulnerability
sudo apt install kali-tools-web
sudo apt install kali-tools-windows-resources
sudo apt install ali-tools-wireless
